name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: python -m unittest discover -s PDF_builder/tests

    - name: Build executable
      run: pyinstaller --clean --distpath ./dist --workpath ./build PDF_builder/resume_builder.spec

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: resume-builder-executable
        path: dist/resume_builder  # Adjust if necessary

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: resume-builder-executable
        path: ./dist

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: 'v0.0.0'  # Adjust the version as necessary
        name: Release v0.0.0
        files: ./dist/resume_builder  # Adjust if necessary
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
