name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile PDF_builder/src/app.py
      # The '--onefile' option creates a single executable file

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: resume-builder-executable
        path: dist/app  # Adjust this if the executable has a different name or path

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: resume-builder-executable
        path: ./dist

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./dist/app  # Adjust this if the executable has a different name or path
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
