name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile PDF_builder/src/app.py

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: resume-builder-executable
        path: dist/app  # Adjust if necessary

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: resume-builder-executable
        path: ./dist

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: '0.0.0'  # Fixed tag version
        name: Release 0.0.0
        files: ./dist/app  # Adjust if necessary
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
