name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fpdf
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover -s tests

    - name: Run application
      run: |
        python app.py
      env:
        DISPLAY: ':99.0'
        GITHUB_ACTIONS: true
